export interface FreeProvider {
  name: string;
  baseURL: string;
  type: "ollama" | "openrouter" | "openai-compatible";
  models: string[];
  priority: number;
  enabled: boolean;
  maxRetries: number;
  timeoutMs: number;
}

export const PROVIDER_REGISTRY: FreeProvider[] = [
  {
    name: "ollama-local",
    baseURL: "http://localhost:11434",
    type: "ollama",
    models: ["goekdenizguelmez/JOSIEFIED-Qwen3:8b", "hf.co/OBLITERATUS/Qwen3.8-27B-OBLITERATED:Q4_K_M", "llama3.1:8b", "qwen2.5:7b", "mistral:7b", "phi3:medium"],
    priority: 1,
    enabled: true,
    maxRetries: 2,
    timeoutMs: 120000,
  },
  {
    name: "openrouter-free",
    baseURL: "https://openrouter.ai/api/v1",
    type: "openrouter",
    models: [
      "openrouter/auto",
      "meta-llama/llama-3.1-8b-instruct:free",
      "google/gemma-2-9b-it:free",
      "mistralai/mistral-7b-instruct:free",
      "nvidia/nemotron-70b-instruct:free",
    ],
    priority: 2,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "openai-compatible",
    baseURL: "",
    type: "openai-compatible",
    models: ["gpt-4o-mini"],
    priority: 99,
    enabled: false,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "groq",
    baseURL: "https://api.groq.com/openai/v1",
    type: "openai-compatible",
    models: ["llama-3.1-8b-instant", "llama-3.1-70b-versatile", "llama-3.2-1b-preview", "llama-3.2-11b-vision-preview", "mixtral-8x7b-32768"],
    priority: 3,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "mistral",
    baseURL: "https://api.mistral.com/v1",
    type: "openai-compatible",
    models: ["mistral-small-latest", "mistral-medium-latest", "mistral-large-latest", "mixtral-8x7b-latest"],
    priority: 4,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "cohere",
    baseURL: "https://api.cohere.com/v1",
    type: "openai-compatible",
    models: ["command-r", "command-r-plus", "command-light"],
    priority: 5,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "huggingface",
    baseURL: "https://api-inference.huggingface.co",
    type: "openai-compatible",
    models: ["HuggingFaceH4/zephyr-7b-beta", "HuggingFaceH4/mistral-7b-it", "bigcode/starcoder2-15b"],
    priority: 6,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "fireworks",
    baseURL: "https://api.fireworks.ai/inference/v1",
    type: "openai-compatible",
    models: ["accounts/fireworks/models/llama-v3-8b-instruct", "accounts/fireworks/models/llama-v3-70b-instruct", "accounts/fireworks/models/mixtral-8x7b-instruct"],
    priority: 7,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "together",
    baseURL: "https://api.together.xyz/v1",
    type: "openai-compatible",
    models: ["meta-llama/Llama-3-8b-hf-chat", "meta-llama/Llama-3-70b-hf-chat", "mistralai/Mixtral-8x7B-Instruct-v0.1", "Qwen/Qwen1.5-7B-Chat"],
    priority: 8,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "deepseek",
    baseURL: "https://api.deepseek.com/v1",
    type: "openai-compatible",
    models: ["deepseek-chat", "deepseek-coder", "deepseek-reasoner"],
    priority: 9,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "gemini",
    baseURL: "https://generativelanguage.googleapis.com/v1/openai",
    type: "openai-compatible",
    models: ["gemini-1.5-flash", "gemini-1.5-pro", "gemini-2.0-flash-exp"],
    priority: 10,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "xai",
    baseURL: "https://api.x.ai/v1",
    type: "openai-compatible",
    models: ["grok-2", "grok-2-mini", "grok-beta", "grok-mini"],
    priority: 11,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "perplexity",
    baseURL: "https://api.perplexity.ai",
    type: "openai-compatible",
    models: ["sonar", "sonar-pro", "sonar-reasoning", "sonar-deep-research"],
    priority: 12,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "cerebras",
    baseURL: "https://api.cerebras.ai/v1",
    type: "openai-compatible",
    models: ["llama3.1-8b", "llama3.1-70b", "llama3.2-1b", "llama3.2-11b-vision", "qwen-32b"],
    priority: 13,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "cloudflare",
    baseURL: "",
    type: "openai-compatible",
    models: ["@cf/meta-llama/llama-3.1-8b-instruct", "@cf/qwen/qwen2.5-7b-instruct", "@cf/mistral/mistral-7b-instruct"],
    priority: 99,
    enabled: false,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "nvidia",
    baseURL: "https://integrate.api.nvidia.com/v1",
    type: "openai-compatible",
    models: ["meta/llama-3.1-8b-instruct", "meta/llama-3.1-70b-instruct", "mistralai/mistral-7b-instruct", "nvidia/nemotron-4-340b-instruct"],
    priority: 14,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "voyage",
    baseURL: "",
    type: "openai-compatible",
    models: ["voyage-3-large", "voyage-3", "voyage-code-3"],
    priority: 99,
    enabled: false,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "jina",
    baseURL: "https://api.jina.ai/v1",
    type: "openai-compatible",
    models: ["jina-embeddings-v3", "jina-clip-v2"],
    priority: 15,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "parasail",
    baseURL: "https://api.parasail.ai/v1",
    type: "openai-compatible",
    models: ["parasail-dqn-turbo-70b", "parasail-mixtral-8x7b", "parasail-llama-3-8b"],
    priority: 16,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
  {
    name: "featherless",
    baseURL: "https://api.featherless.ai/v1",
    type: "openai-compatible",
    models: ["featherless/qwen-2.5-7b-instruct", "featherless/llama-3.1-8b-instruct", "featherless/mistral-7b-instruct"],
    priority: 17,
    enabled: true,
    maxRetries: 3,
    timeoutMs: 120000,
  },
];

export function getProvider(name: string): FreeProvider | undefined {
  return PROVIDER_REGISTRY.find((p) => p.name === name);
}
